CREATE TABLE CLIENT (
    ID NUMERIC(10) NOT NULL CONSTRAINT ID_CLIENT_PK PRIMARY KEY,
    FIRST_NAME VARCHAR(80) NOT NULL,
    LAST_NAME VARCHAR(80) NOT NULL,
    SOCIAL_SECURITY_NO VARCHAR(20),
    ADDRESS VARCHAR(100),
    JOINING_DATE TIMESTAMP NOT NULL,
    VERSION INTEGER DEFAULT 1 NOT NULL
);

CREATE SEQUENCE CLIENT_SEQ
    START WITH 1
    INCREMENT BY 1;