CREATE TABLE CLIENT (
    ID NUMBER(10,0) NOT NULL CONSTRAINT ID_PK PRIMARY KEY,
    FIRST_NAME VARCHAR2(80 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(80 CHAR) NOT NULL,
    SOCIAL_SECURITY_NO VARCHAR2(20 CHAR),
    ADDRESS VARCHAR2(100 CHAR),
    JOINING_DATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE CLIENT_SEQ
    START WITH     1
    INCREMENT BY   1
    NOCACHE
    NOCYCLE;